server:
  port: 9528

# sentinel+gataway整合Case
spring:
  application:
    name: cloud-alibaba-sentinel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
#      discovery:
#        # 开启根据服务名称自动转发
#        locator:
#          enabled: true
#          # 微服务名称以小写形式呈现
#          lower-case-service-id: true
      # pay_routh1
      routes:
        # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
        - id: pay_routh1
          # 匹配后提供服务的路由地址
          uri: lb://nacos-payment-provider
          # uri: http://localhost:9001
          # 断言
          predicates:
            # 路径相匹配的进行路由
            - Path=/pay/**