server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  # Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 优先使用服务ip进行注册
        prefer-ip-address: true
        service-name: ${spring.application.name}